version: '3.1'

services:

  nginx:
    container_name: on-boarding-nginx
    image: nginx
    ports:
     - 80:80
     - 443:443
    volumes:
      - ../:/app
      - ./etc/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    restart: always

  composer:
    container_name: composer
    image: composer
    command: composer update
    volumes:
      - ../:/app
    depends_on:
      - php

  php:
    container_name: on-boarding-php
    build: php
    expose:
      - 9001
    volumes:
      - ../:/app
      - ./etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    working_dir: /app
    environment:
        XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST}

  postgres:
    container_name: on-boarding-postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.data/:/var/lib/postgresql